// get create task
export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";

// get all task
export const GET_ALL_TASK_REQUEST = "GET_ALL_TASK_REQUEST";
export const GET_ALL_TASK_SUCCESS = "GET_ALL_TASK_SUCCESS";
export const GET_ALL_TASK_FAILURE = "GET_ALL_TASK_FAILURE";

// get single task with id
export const GET_SINGLE_TASK_REQUEST = "GET_SINGLE_TASK_REQUEST";
export const GET_SINGLE_TASK_SUCCESS = "GET_SINGLE_TASK_SUCCESS";
export const GET_SINGLE_TASK_FAILURE = "GET_SINGLE_TASK_FAILURE";

// update the with id  task
export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE";  
// Delete task
export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";